#version: '3.9'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABASE: health 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -u root -p password"]
      interval: 3s
      timeout: 3s
      retries: 5
    
  frontend:
      build: ./frontend
      container_name: frontend_c
      ports:
        - '3000:3000'
  backend:
      build: ./backend
      container_name: backend_c
      ports:
        - '4000:4000'
      stdin_open: true
      tty: true
      depends_on:
        - db
      
      environment:
        - DB_HOST=db
volumes:
      db_data: